# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
