# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.image_upload_to),
        ),
    ]
