# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170322_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.AddField(
            model_name='variation',
            name='inventory',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
        ),
    ]
